<?php

namespace Webbook\MainBundle\Repository;

/**
 * BlockOptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockOptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
