<?php

namespace Webbook\MainBundle\Repository;

/**
 * BlockHistoricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockHistoricRepository extends \Doctrine\ORM\EntityRepository
{
}
