<?php

namespace Webbook\MainBundle\Repository;

/**
 * BookHasAuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookHasAuthorRepository extends \Doctrine\ORM\EntityRepository
{
}
