<?php

namespace Webbook\MainBundle\Repository;

/**
 * BookStructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookBlockRepository extends \Doctrine\ORM\EntityRepository
{

    public function hasUserPermission($block,$user,$permissions,$limited=false){
        $query =$this->createQueryBuilder('bl')
            ->join("MainBundle:Authorization","a","with","a.bookBlock = bl.id")
            ->join("UserBundle:User","u","with","a.user= u.id")
            ->where("u.id = :user")
            ->andWhere('bl.id = :block');
            if($limited)
                $query->andWhere('a.limited = false');
            if($permissions['r']!==false)
                $query->andWhere('a.canRead = true');
            if($permissions['w']!==false)
                $query->andWhere('a.canWrite = true');
            if($permissions['d']!==false)
                $query->andWhere('a.canDelete = true');
            if($permissions['v']!==false)
                $query->andWhere('a.canValidate = true');

            $res=$query->setParameters(["user"=>$user,"block"=>$block])
                ->getQuery()->getResult();
        return count($res)>0;
    }
}
