<?php

namespace Webbook\MainBundle\Repository;

/**
 * BookEditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookEditionRepository extends \Doctrine\ORM\EntityRepository
{
}
