<?php

namespace Webbook\MainBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotEmpty(){

        return $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('c.books','b')
            ->having('COUNT(b.id)>0')
            ->groupBy('b.id')
            ->getQuery()->getResult();
    }
}
