<?php

namespace Webbook\MainBundle\Repository;

/**
 * NewsLetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsLetterRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllQuery(){

        return $this->createQueryBuilder('nl')
            ->orderBy('nl.createdAt','DESC')
            ->getQuery();

    }
}
