<?php

namespace Webbook\MainBundle\Repository;

/**
 * ValidationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidationRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
