<?php

namespace Webbook\MessagingBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{


    public function getSentMessageByDateQuery($user_id,$date){
        return $this->createQueryBuilder("m")
            ->where('m.sender = :user')
            ->andWhere('m.dateSend like :date')
            ->andWhere('m.deletedAt is NULL')
            ->orderBy('m.dateSend','DESC')
            ->setParameters(['user'=>$user_id,'date'=>'%'.$date.'%'])
            ->getQuery();
    }

    public function getImportantMessageByDateQuery($user_id,$date){
        return $this->createQueryBuilder("m")
            ->select('m')
            ->join('MessagingBundle:UserHasMessage','uhm','uhm.message = m.id')
            ->andWhere('uhm.important = true')
            ->where('m.sender = :user')
            ->andWhere('m.dateSend like :date')
            ->orderBy('m.dateSend','DESC')
            ->setParameters(['user'=>$user_id,'date'=>'%'.$date.'%'])
            ->getQuery();
    }

    public function getDeletedMessageByDateQuery($user_id,$date){
        return $this->createQueryBuilder("m")
            ->select('m')
            ->join('MessagingBundle:UserHasMessage','uhm','uhm.message = m.id')
            ->andWhere('uhm.deleted = true')
            ->where('m.sender = :user')
            ->andWhere('m.dateSend like :date')
            ->orderBy('m.dateSend','DESC')
            ->setParameters(['user'=>$user_id,'date'=>'%'.$date.'%'])
            ->getQuery();
    }

    public function getDraftMessageByDateQuery($user_id,$date){
        return $this->createQueryBuilder("m")
            ->select('m')
            ->andWhere('m.sent = false')
            ->andWhere('m.dateSend like :date')
            ->orderBy('m.dateSend','DESC')
            ->setParameters(['user'=>$user_id,'date'=>'%'.$date.'%'])
            ->getQuery();
    }
}
