<?php

namespace Webbook\MessagingBundle\Repository;

/**
 * UserHasMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasMessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInboxMessageByDateQuery($user_id,$date){
        return $this->createQueryBuilder("uhm")
            ->select('uhm')
            ->join('MessagingBundle:Message','m','uhm.message = message.id')
            ->where('uhm.receiver = :user')
            ->andWhere('uhm.deleted = false')
            ->andWhere('m.dateSend like :date')
            ->orderBy('m.dateSend','DESC')
            ->setParameters(['user'=>$user_id,'date'=>'%'.$date.'%'])
            ->getQuery();
    }
    public function getLastInboxMessage($user,$limit=10){
        return $this->createQueryBuilder("uhm")
            ->select('uhm')
            ->join('MessagingBundle:Message','m','uhm.message = message.id')
            ->where('uhm.receiver = :user')
            ->andWhere('uhm.deleted = false')
            ->setParameter('user',$user)
            ->orderBy('m.dateSend','DESC')
            ->setMaxResults($limit)
            ->getQuery()->getResult();
    }
}
