# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    debug.stopwatch:
        class:        Symfony\Component\Stopwatch\Stopwatch

    tree.twig.extension:
        class:        Fuz\Jordan\Twig\Extension\TreeExtension
        tags:
             - { name: 'twig.extension' }

    twig.extension.sortbyfield:
        class: Snilius\Twig\SortByFieldExtension
        tags:
            - { name: twig.extension }

    app.form.registration:
        class: Core\UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }