fos_user_security_login:
    path:   /login
    defaults: { _controller: UserBundle:Security:login }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_security_check:
    path:     /login_check
    defaults: { _controller: UserBundle:Security:check }

api_fos_user_security_check:
    path:     /api/login_check
    defaults: { _controller: UserBundle:Security:check }

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: UserBundle:Security:logout }
    methods: [GET]

get_user_messages:
    path:    /user/messages
    defaults: { _controller: MessagingBundle:Default:getUserMessages }
    options:
        expose:  true