
services:
    acme_api.event.jwt_created_listener:
        class: Core\UserBundle\Listener\JWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    acme_api.event.jwt_decoded_listener:
        class: Core\UserBundle\Listener\JWTDecodedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }

    acme_api.event.authentication_success_listener:
        class: Core\UserBundle\Listener\JWTResponseListener
        arguments:  ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    login_success_handler:
        class:      Core\UserBundle\Security\Authentication\Handler\LoginSuccessHandler
        arguments:  ["@router", "@security.authorization_checker"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }