<?php

namespace Webbook\NotificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function findByDateAndUserAndUrl($date,$user,$url){

        return $this->createQueryBuilder('n')
            ->where('n.administrator = :administrator')
            ->andWhere('n.date like :date')
            ->andWhere('n.url = :url')
            ->setParameters(['administrator'=>$user,'date'=>'%'.$date.'%','url'=>$url])
            ->getQuery()->getResult();


    }
}
