<?php

namespace Core\UserBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findByRoles($roles,$user=null ){
        $result= $this->createQueryBuilder("u");
        foreach ($roles as $key => $role)
            $result->orWhere('u.roles  LIKE :role'.$key);
        $result/*->andWhere('u.roles not LIKE :roleAdmin')*/
            ->andWhere('u.enabled = 1');
        foreach ($roles as $key => $role)
            $result->setParameter('role'.$key, '%"' . $role . '"%');
        /*$result->setParameter('roleAdmin','%ROLE_SUPER_ADMIN%');*/
        if($user)
            $result->andWhere('u.id != :me')->setParameter('me',$user);
        return $result->getQuery()->getResult();
    }

    public function findClients(){
        $result= $this->createQueryBuilder("u")
            ->where('u.roles  LIKE :role')
            ->setParameter('role', '%ROLE_CLIENT%');
        return $result->getQuery()->getResult();
    }
}
